[package]
name = "anchor-introspection-derive"
version = "0.1.0"
edition = "2021"

[lib]
name = "anchor_introspection_derive"
proc-macro = true

[dependencies]
syn = "1"
quote = "1"
anchor-lang = "0.29.0"
sha2 = "0.10.0"