[package]
name = "anchor-introspection"
authors = ["Dean Little <@deanmlittle>"]
version = "0.1.0"
edition = "2021"

[lib]
name = "anchor_introspection"

[dependencies] 
anchor-lang = "0.29.0"
anchor-introspection-derive = { path = "../anchor-introspection-derive" }
